site_name: Telegram bot
site_url: https://tgbot.vendeli.eu/
repo_url: https://github.com/vendelieu/telegram-bot
repo_name: vendelieu/telegram-bot
site_description: >-
  Telegram Bot API wrapper with handy Kotlin DSL.

nav:
  - Home: index.md
  - Documentation:
      - ...
  - API Reference: https://vendelieu.github.io/telegram-bot/

theme:
  name: material
  language: en
  logo: assets/img/lib-logo.png
  favicon: assets/img/lib-logo.png
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.share
    - toc.follow
  icon:
    repo: fontawesome/brands/github
extra_css:
  - assets/stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-NV2HD45F9G
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: ["."]
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - toc:
      title: On this page
      permalink: true
plugins:
  - awesome-pages
  - gh-admonitions
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          name: English
          default: true
#        - locale: ar
#          name: عربى
#          build: true
        - locale: zh
          name: 中文
          build: true
          site_name: Telegram bot 中文文档
          site_description: 带有便捷 Kotlin DSL 的 Telegram Bot API 封装程序。
          nav_translations:
            Home: 首页
            Documentation: 文件
            API Reference: API 参考
#        - locale: ko
#          name: Korean
#          build: true
#        - locale: ja
#          name: 日本語
#          build: true
#        - locale: id
#          name: Bahasa Indonesia
#          build: true
#        - locale: pt
#          name: Português
#          build: true
#        - locale: es
#          name: Español
#          build: true
#        - locale: fr
#          name: Français
#          build: true
#        - locale: ru
#          name: Русский
#          build: true
  - search:
      { separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;' }
  - minify_html