name: Organize documents
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  source:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade deepl

      - name: Clone TelegramBot wiki repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'vendelieu'
          repository: 'telegram-bot.wiki'

      - name: Reorganize files
        run: |
          sudo mv -f ./telegram-bot.wiki/* ./docs/ 
          sudo mv ./docs/Home.md ./docs/index.md
          sudo rm -rf ./telegram-bot.wiki 
          sudo rm -rf ./docs/_Footer.md

      - name: Find and Replace links
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "https://github.com/vendelieu/telegram-bot/wiki/(.*)"
          replace: "/$1"
          include: "docs/**"

      - name: Add titles
        run: python generate_titles.py

#      - name: Translate Markdown files
#        run: |
#          python translate.py [sourcefile] [outputdirectory] [languagedictionary] "FR,AR,RU,ES,ZH-HANS,KO,JA,ID,PT-BR"
#        env:
#          DEEPL_AUTH_KEY: ${{ secrets.DL_API_KEY }}

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit sources.
          branch: master