name: Translate Markdown Files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 0"

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          yarn install
          yarn add i18n-ai-translate

      - name: Translate Markdown files
        run: |
          # Define the languages you want to translate to
          LANGUAGES=("fr" "ar" "ru" "es" "zh" "ko" "ja" "id" "br")

          # Loop through each Markdown file in the docs directory
          for file in docs/*.md; do
            # Check if the file has a two-letter language suffix
            if [[ ! "$file" =~ \.[a-z]{2}\.md$ ]]; then
              for lang in "${LANGUAGES[@]}"; do
                # Define output file name with language suffix
                output_file="${file%.md}.$lang.md"
          
                # Translate the file using Gemini
                npx i18n-ai-translate translate -i "$file" -o "$output_file" --engine gemini --model gemini-pro --api-key ${{ secrets.GEMINI_API_KEY }}
              done
            fi
          done

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit translated files.
          branch: master